# Generated by Django 5.1.4 on 2024-12-10 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "owner",
                    models.UUIDField(
                        default=uuid.UUID("96352507-0789-4feb-8d36-f0f8e6c1bdaf")
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Specific dates"), (2, "Days of the week")],
                        default=2,
                    ),
                ),
                ("startTime", models.CharField(max_length=200)),
                ("endTime", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, primary_key=True, serialize=False),
                ),
                ("date", models.DateField(default="")),
                ("dayOfWeek", models.CharField(default="", max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="api.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respondent",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("isGuestUser", models.BooleanField()),
                (
                    "participatedEvent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participatedEvent",
                        to="api.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField()),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respondent",
                        to="api.respondent",
                    ),
                ),
            ],
        ),
    ]
