# Generated by Django 5.1.4 on 2025-01-27 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('1bddd341-799f-4d15-bff9-e3a2344909ae'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('06631247-928e-476f-99da-7288456611c6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('3979bf12-a8e7-4a84-afb4-de92e20a0b00'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('7778d260-6cae-4c3e-894d-38eb8da895d5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('4d25257f-5ee3-46c2-bcc2-6a7481b24220'), primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('type', 1), ('type', 2), _connector='OR'), name='Type constraint', violation_error_message='Integer type must be either 1 or 2.'),
        ),
    ]
