# Generated by Django 5.1.4 on 2025-01-28 07:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('ef2a62e9-35be-437f-8d16-163ee01c6502'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('c2537595-84d3-438e-814d-178d1159afb8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('5c7fe7d9-09b1-422d-b0c5-c651d198ac4f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('d335c29c-2174-4afc-8282-6ebaa9cf505a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('41857fbf-e63b-401b-a2e1-2ed2e9404bf3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator(message='name cannot be empty.', regex='^(?!\\s*$).+')]),
        ),
    ]
