# Generated by Django 5.1.4 on 2024-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_date_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.CharField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
