# Generated by Django 5.1.4 on 2025-01-27 12:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_availability_id_alter_date_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('7c17ce67-f769-41b1-88f3-2e7a715d251c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('23b016f2-9122-4cd6-80bc-e1db26a1a62c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('34712d3b-5a1e-4478-bdbd-352760020011'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time_utc',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Valid time should end with '00'", regex=':00$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('ec925d42-43d0-44ee-8aea-2b9cc6da7c7f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time_utc',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Valid time should end with '00'", regex=':00$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('2036e365-6dd7-47cd-9d2e-c06b392bc612'), primary_key=True, serialize=False),
        ),
    ]
