# Generated by Django 5.1.4 on 2025-01-29 13:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_availability_id_alter_date_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('c2f85947-60e2-4426-83c5-fdad81f75e43'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Valid availability time must be one of the following formats - 09:00 or 09:30', regex='(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):00$|(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):30$')]),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('64075bef-1dd9-4009-b6ba-07e5772932ac'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('c2853470-4818-458e-b5d6-57cdd99252bc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('33877052-029c-4b53-8d9e-61fa94f148f4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('6fd07d78-58d7-42cd-a1dc-4063c12a774d'), primary_key=True, serialize=False),
        ),
    ]
