# Generated by Django 5.1.4 on 2024-12-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respondent",
            name="id",
            field=models.CharField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
