# Generated by Django 5.1.4 on 2025-01-29 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_availability_id_alter_availability_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('9150c409-9fae-48b4-bd96-d211b8b044de'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('4a1a25b2-4036-4494-bd2d-7289de28db4e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('3cbb5a08-f668-4f87-80a4-d7f907f8587f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('29d6b5c0-61f6-467b-981e-94c7417cd7e8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('1b7a5810-a0ae-4aca-8170-219c0a1be0e2'), primary_key=True, serialize=False),
        ),
    ]
