# Generated by Django 5.1.4 on 2024-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_respondent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="id",
            field=models.CharField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="date",
            name="id",
            field=models.CharField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
