# Generated by Django 5.1.4 on 2025-01-30 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_availability_id_alter_date_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('d8d0d43d-e054-46e7-9a4d-bf4b94b934b0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('936e8919-d3cc-4808-8dd5-3dc9d9d96059'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('2ea238cb-cd65-40d9-b54f-d768b647c565'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('be2d11c0-88de-4068-a6a8-7f02835edb55'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Specific dates'), (2, 'Days of the week')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('3e3ddc17-eca0-4bb7-976d-d30aa60465b9'), primary_key=True, serialize=False),
        ),
    ]
