# Generated by Django 5.1.4 on 2025-01-31 08:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_availability_id_alter_date_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('ceef4a29-10f5-46ec-a8f1-9b3170774d5d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(default='2020-01-28 09:00', validators=[django.core.validators.RegexValidator(message='Valid availability time must be one of the following formats - 09:00 or 09:30', regex='^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])\\s(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):00$|(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):30$')]),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('692ee57b-b3c1-454a-a32b-0e4919e4fb50'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('9f34e8b1-cea2-4cdf-b092-8a5ef6a6bdfd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time_utc',
            field=models.CharField(default='10:00', max_length=200, validators=[django.core.validators.RegexValidator(message="Please format in hh:mm. It should end with '00'", regex='(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):00$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('b963a1ac-f4d0-4b09-950d-b58d444bb70b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time_utc',
            field=models.CharField(default='09:00', max_length=200, validators=[django.core.validators.RegexValidator(message="Please format in hh:mm. It should end with '00'", regex='(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):00$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('3e5e06de-b04f-4a5f-91db-33e169425e6d'), primary_key=True, serialize=False),
        ),
    ]
