# Generated by Django 5.1.4 on 2024-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_availability_id_alter_date_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="date",
            field=models.DateField(blank=True, default="", max_length=100, null=True),
        ),
    ]
