# Generated by Django 5.1.4 on 2025-02-01 04:43

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_availability_id_alter_availability_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('cb66f679-5b3a-4ebf-9c62-5ff1cf389092'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Valid availability time must be one of the following formats - yyyy-mm-dd 09:00 or yyyy-mm-dd 09:30', regex='((Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)|^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01]))\\s(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):00$|(0[0-9]{1}|1[0-9]{1}|2[0-3]{1}):30$')]),
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('0f109ce7-deea-47dc-8cea-6cb1bf7c7bdf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('ec85bcb6-9959-4b55-ab92-508da3e5db37'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('2ec5ba16-cdf5-46f7-9161-31f4ec36f096'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('c5ffc57b-e562-4f43-a6f9-202c4d59d688'), primary_key=True, serialize=False),
        ),
    ]
