# Generated by Django 5.1.4 on 2024-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_date_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="time",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="date",
            name="date",
            field=models.DateField(
                blank=True, default="1900-01-01", max_length=100, null=True
            ),
        ),
    ]
